name: $(BuildDefinitionName)-$(date:yyMM).$(date:dd)$(rev:rrr)
trigger: none
pr: none

variables:
  - group: ESRP
  - group: GithubTestingFeedCreds
  # Prevents auto-injection of nuget-security-analysis (not needed for open source projects)
  - name: skipNugetSecurityAnalysis
    value: true

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance

stages:
- stage: Build
  displayName: Build PSResourceGet Module Package
  jobs:
  - job: BuildPkg
    displayName: Build Package
    pool:
      name: 1ES
      demands:
      - ImageOverride -equals PSMMS2019-Secure

    steps:
    - pwsh: |
        Get-ChildItem -Path env:
        Get-ChildItem -Path . -Recurse -Directory
      displayName: Capture environment for build
      condition: succeededOrFailed()

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        if (Test-Path -Path $modulePath) {
          Write-Verbose -Verbose "Deleting existing temp module path: $modulePath"
          Remove-Item -Path $modulePath -Recurse -Force -ErrorAction Ignore
        }
        if (! (Test-Path -Path $modulePath)) {
          Write-Verbose -Verbose "Creating new temp module path: $modulePath"
          $null = New-Item -Path $modulePath -ItemType Directory
        }
      displayName: Create temporary module path

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        Write-Verbose -Verbose "Install PSResourceGet to temp module path"
        Save-Module -Name PowerShellGet -MinimumVersion 3.0.18-beta18 -Path $modulePath -AllowPrerelease -Force
      displayName: Install PowerShellGet v3

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        #
        # Build for net472 framework
        $(Build.SourcesDirectory)/build.ps1 -Build -Clean -BuildConfiguration Release -BuildFramework 'net472'
      displayName: Build and publish artifact

    - pwsh: |
        $signSrcPath = "$($config.BuildOutputPath)"
        $vstsCommandString = "vso[task.setvariable variable=signSrcPath]${signSrcPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
        #
        $outSignPath = "$($config.BuildOutputPath)"
        $vstsCommandString = "vso[task.setvariable variable=signOutPath]${outSignPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
      displayName: Create fake source and output variables for signing template and no signing
      condition: and(succeeded(), eq(variables['SkipSigning'], 'True'))

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        $config = Get-BuildConfiguration

        $signOutPath = "$($config.SignedOutputPath)\$($config.ModuleName)"
        if (! (Test-Path -Path $signOutPath)) {
          $null = New-Item -Path $signOutPath -ItemType Directory
        }

        # Third party files signing directory
        $srcPath = "$($config.BuildOutputPath)\$($config.ModuleName)"
        $thirdPartySignSrcPath = "$($config.BuildOutputPath)\ThirdParty"
        if (! (Test-Path -Path $thirdPartySignSrcPath)) {
          $null = New-Item -Path $thirdPartySignSrcPath -ItemType Directory -Verbose
        }

        # dependency directory
        $depsPath = Join-Path -Path $thirdPartySignSrcPath -ChildPath "dependencies"
        if (! (Test-Path -Path $depsPath)) {
          $null = New-Item -Path $depsPath -ItemType Directory -Verbose
        }
        Get-ChildItem -Path (Join-Path -Path $srcPath -ChildPath "dependencies") -Filter '*.dll' | Foreach-Object {
          if ($_.Name -ne 'Microsoft.PowerShell.PSResourceGet.dll') {
            $sig = Get-AuthenticodeSignature -FilePath $_.FullName
            if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notlike '*Microsoft*' -or $sig.SignerCertificate.Issuer -notlike '*Microsoft Code Signing PCA*') {
              # Copy for third party signing
              Copy-Item -Path $_.FullName -Dest $depsPath -Force -Verbose
            }
          }
        }

        # Set signing src path variable
        $vstsCommandString = "vso[task.setvariable variable=signSrcPath]${thirdPartySignSrcPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"

        # Set signing out path variable
        $vstsCommandString = "vso[task.setvariable variable=signOutPath]${signOutPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
      displayName: Set up for module third party files code signing
      condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True'))

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        $config = Get-BuildConfiguration

        $thirdPartySignSrcPath = "$($config.BuildOutputPath)\ThirdParty"
        Get-ChildItem -Path $thirdPartySignSrcPath -Recurse
      displayName: Capture third party files for signing
      condition: succeededOrFailed()

    - template: EsrpSign.yml@ComplianceRepo
      parameters:
        buildOutputPath: $(signSrcPath)
        signOutputPath: $(signOutPath)
        certificateId: "CP-231522"
        pattern: |
          **\*.dll
        useMinimatch: true

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        $config = Get-BuildConfiguration

        $signOutPath = "$($config.SignedOutputPath)\$($config.ModuleName)"
        Get-ChildItem -Path $signOutPath -Recurse
      displayName: Capture third party signed files output
      condition: succeededOrFailed()

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force

        $config = Get-BuildConfiguration

        $srcPath = "$($config.BuildOutputPath)\$($config.ModuleName)"
        $signOutPath = "$($config.SignedOutputPath)\$($config.ModuleName)"
        if (! (Test-Path -Path $signOutPath)) {
          $null = New-Item -Path $signOutPath -ItemType Directory
        }

        # Copy Notice.txt
        Copy-Item -Path (Join-Path -Path $srcPath -ChildPath "Notice.txt") -Dest $signOutPath
        # Copy LICENSE
        Copy-Item -Path (Join-Path -Path $srcPath -ChildPath "LICENSE") -Dest $signOutPath

        # dependency directory
        $depsSignedOutPath = Join-Path -Path $signOutPath -ChildPath "dependencies"
        if (! (Test-Path -Path $depsSignedOutPath)) {
          $null = New-Item -Path $depsSignedOutPath -ItemType Directory -Verbose
        }
        Get-ChildItem -Path (Join-Path -Path $srcPath -ChildPath "dependencies") -Filter '*.dll' | Foreach-Object {
          if ($_.Name -ne 'Microsoft.PowerShell.PSResourceGet.dll') {
            $sig = Get-AuthenticodeSignature -FilePath $_.FullName
            if ($sig.Status -eq 'Valid' -and ($sig.SignerCertificate.Subject -like '*Microsoft*' -and $sig.SignerCertificate.Issuer -like '*Microsoft Code Signing PCA*')) {
              # Copy already signed files directly to output
              Copy-Item -Path $_.FullName -Dest $depsSignedOutPath -Force -Verbose
            }
          }
        }
      displayName: Copy already properly signed third party files
      condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True'))

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        $config = Get-BuildConfiguration

        $signOutPath = "$($config.SignedOutputPath)\$($config.ModuleName)"
        Get-ChildItem -Path $signOutPath -Recurse
      displayName: Capture other third party files copied
      condition: succeededOrFailed()

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force

        $config = Get-BuildConfiguration

        # Created files signing directory
        $srcPath = "$($config.BuildOutputPath)\$($config.ModuleName)"
        $createdSignSrcPath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'CreatedFiles'
        if (! (Test-Path -Path $createdSignSrcPath)) {
          $null = New-Item -Path $createdSignSrcPath -ItemType Directory -Verbose
        }
        Copy-Item -Path (Join-Path -Path $srcPath -ChildPath "Microsoft.PowerShell.PSResourceGet.psd1") -Dest $createdSignSrcPath -Force -Verbose
        Copy-Item -Path (Join-Path -Path $srcPath -ChildPath "PSGet.Format.ps1xml") -Dest $createdSignSrcPath -Force -Verbose
        Copy-Item -Path (Join-Path -Path $srcPath -ChildPath "Microsoft.PowerShell.PSResourceGet.dll") -Dest $createdSignSrcPath -Force -Verbose

        $signOutPath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'CreatedFilesOut'
        if (! (Test-Path -Path $signOutPath)) {
          $null = New-Item -Path $signOutPath -ItemType Directory
        }

        # Set signing src path variable
        $vstsCommandString = "vso[task.setvariable variable=signSrcPathCreated]${createdSignSrcPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"

        # Set signing out path variable
        $vstsCommandString = "vso[task.setvariable variable=signOutPathCreated]${signOutPath}"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
      displayName: Set up for module created files code signing
      condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True'))

    - pwsh: |
        $createdSignSrcPath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'CreatedFiles'
        Get-ChildItem -Path $createdSignSrcPath -Recurse
      displayName: Capture created files to sign source
      condition: succeededOrFailed()

    - pwsh: |
        Get-ChildItem -Path env:
      displayName: Capture environment for created files signing
      condition: succeededOrFailed()

    - template: EsrpSign.yml@ComplianceRepo
      parameters:
        buildOutputPath: $(signSrcPathCreated)
        signOutputPath: $(signOutPathCreated)
        certificateId: "CP-230012"
        pattern: |
          **\*.dll
          **\*.psd1
          **\*.psm1
          **\*.ps1xml
        useMinimatch: true

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        $config = Get-BuildConfiguration

        $signSrcPath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'CreatedFilesOut'
        $signOutPath = "$($config.SignedOutputPath)\$($config.ModuleName)"
        Copy-Item -Path "$signSrcPath/*" -Dest $signOutPath -Recurse -Force -Verbose
      displayName: Copy signed created files to output
      condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), ne(variables['SkipSigning'], 'True'))

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        $config = Get-BuildConfiguration

        $signOutPath = "$($config.SignedOutputPath)\$($config.ModuleName)"
        Get-ChildItem -Path $signOutPath -Recurse
      displayName: Capture all signed files output
      condition: succeededOrFailed()

    - ${{ if ne(variables.SkipSigning, 'True') }}:
      - template: Sbom.yml@ComplianceRepo
        parameters:
          BuildDropPath: $(signOutPath)
          Build_Repository_Uri: 'https://github.com/powershell/PSResourceGet'
          PackageName: 'Microsoft.PowerShell.PSResourceGet'
          PackageVersion: '0.5.22-beta22'

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force
        #
        if ($env:SkipSigning -eq 'True')
        {
          $(Build.SourcesDirectory)/build.ps1 -Publish
        }
        else
        {
          $(Build.SourcesDirectory)/build.ps1 -Publish -Signed
        }
      displayName: Publish module nuget package and upload package artifact
      condition: succeeded()

    - pwsh: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name $(Build.SourcesDirectory)/buildtools.psd1 -Force

        $config = Get-BuildConfiguration
        $artifactName = "$($config.ModuleName)"
        if ($env:SkipSigning -eq 'True')
        {
          $srcModulePath = Resolve-Path -Path "$($config.BuildOutputPath)/$($config.ModuleName)"
          Get-ChildItem $srcModulePath
          Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName;]$srcModulePath"
          #
          $(Build.SourcesDirectory)/build.ps1 -Publish
        }
        else
        {
          $srcModulePath = Resolve-Path -Path "$($config.SignedOutputPath)/$($config.ModuleName)"
          Get-ChildItem $srcModulePath
          Write-Host "##vso[artifact.upload containerfolder=$artifactName;artifactname=$artifactName;]$srcModulePath"
          #
          $(Build.SourcesDirectory)/build.ps1 -Publish -Signed
        }
      displayName: Upload module artifact

- stage: Compliance
  displayName: Compliance
  dependsOn: Build
  jobs:
  - job: ComplianceJob
    pool:
      name: 1ES
      demands:
      - ImageOverride -equals PSMMS2019-Secure

    steps:
    - checkout: self
      clean: true
    - checkout: ComplianceRepo
      clean: true
    - download: current
      artifact: 'Microsoft.PowerShell.PSResourceGet'
    - template: assembly-module-compliance.yml@ComplianceRepo
      parameters:
        # binskim
        AnalyzeTarget: '$(Pipeline.Workspace)/Microsoft.PowerShell.PSResourceGet/Microsoft.PowerShell.PSResourceGet.dll'
        AnalyzeSymPath: 'SRV*'
        # component-governance
        sourceScanPath: '$(Build.SourcesDirectory)'
        # credscan
        suppressionsFile: ''
        # TermCheck
        optionsRulesDBPath: ''
        optionsFTPath: ''
        # tsa-upload
        codeBaseName: 'PowerShellGet_210306'
        # selections
        APIScan: false # set to false when not using Windows APIs
    # Generate the third party notice file after component detection
    - task: msospo.ospo-extension.8d7f9abb-6896-461d-9e25-4f74ed65ddb2.notice@0
      displayName: 'Third Party Notice File Generator'
      inputs:
        outputfile: ThirdPartyNotice
        # output format can be html or text
        outputformat: text

- stage: Test
  displayName: Test Package
  dependsOn: Build
  jobs:
  - template: test.yml
    parameters:
      jobName: TestPkgWin
      displayName: PowerShell Core on Windows
      imageName: windows-latest

  - template: test.yml
    parameters:
      jobName: TestPkgWinPS
      displayName: Windows PowerShell on Windows
      imageName: windows-latest
      powershellExecutable: powershell

  - template: test.yml
    parameters:
      jobName: TestPkgUbuntu
      displayName: PowerShell Core on Ubuntu
      imageName: ubuntu-latest

  - template: test.yml
    parameters:
      jobName: TestPkgWinMacOS
      displayName: PowerShell Core on macOS
      imageName: macOS-latest

- stage: Release
  displayName: Publish Package to PSGallery
  condition: and(and(succeeded(), eq(variables['Build.Reason'], 'Manual')), eq(variables['Publish'], 'True'))
  jobs:
  - template: release.yml
