# Mirror github ThreadJob repo to this release pipeline repo at the provided schedule
#

trigger: none
pr: none

schedules:
# You can use https://crontab.guru/#0_8_*_*_* to figure out your crontab expression
# Mirror repo every day at 8 am
- cron: 0 8 * * *
  branches:
    include:
    - refs/heads/master
  always: true

resources:
  repositories:
    - repository: PowerShellGet
      type: git
      name: PowerShellGetV3
      ref: master
    - repository: PowerShellGet-gh
      ref: master
      type: github
      endpoint: ComplianceGHRepo
      name: PowerShell/PowerShellGet

stages:
  - template: ./mirrorTemplates/githubMirror.yml
    parameters:
      repoName: PowerShellGet
