parameters:
  jobName: TestPkgWin
  imageName: windows-latest
  displayName: PowerShell Core on Windows
  powershellExecutable: pwsh
  buildDirectory: '.'
  useAzAuth: false

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}
  steps:
  - ${{ parameters.powershellExecutable }}: |
        Install-Module -Name 'Microsoft.PowerShell.SecretManagement' -force -SkipPublisherCheck -AllowClobber
        Install-Module -Name 'Microsoft.PowerShell.SecretStore' -force -SkipPublisherCheck -AllowClobber
        $vaultPassword = ConvertTo-SecureString $("a!!"+ (Get-Random -Maximum ([int]::MaxValue))) -AsPlainText -Force
        Set-SecretStoreConfiguration -Authentication None -Interaction None -Confirm:$false -Password $vaultPassword
        Register-SecretVault -Name SecretStore -ModuleName Microsoft.PowerShell.SecretStore -DefaultVault
    displayName: Install Secret store
    condition: eq(${{ parameters.useAzAuth }}, false)

  - task: NuGetAuthenticate@1
    displayName: Install Azure Artifacts Credential Provider
    inputs:
      forceReinstallCredentialProvider: true

  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifacts'
    inputs:
      buildType: current
      downloadType: specific
      itemPattern: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - ${{ parameters.powershellExecutable }}: |
      Get-ChildItem -Path "$(System.ArtifactsDirectory)"
    displayName: Capture artifacts directory

  - ${{ parameters.powershellExecutable }}: |
      $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
      if (Test-Path -Path $modulePath) {
        Write-Verbose -Verbose "Deleting existing temp module path: $modulePath"
        Remove-Item -Path $modulePath -Recurse -Force -ErrorAction Ignore
      }
      if (! (Test-Path -Path $modulePath)) {
        Write-Verbose -Verbose "Creating new temp module path: $modulePath"
        $null = New-Item -Path $modulePath -ItemType Directory
      }
    displayName: Create temporary module path

  - ${{ parameters.powershellExecutable }}: |
      $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
      Write-Verbose -Verbose "Install Microsoft.PowerShell.PSResourceGet to temp module path"
      Save-Module -Name Microsoft.PowerShell.PSResourceGet -Path $modulePath -Force -Verbose
      Write-Verbose -Verbose "Install Pester 4.X to temp module path"
      Save-Module -Name "Pester" -MaximumVersion 4.99 -Path $modulePath -Force
    displayName: Install Microsoft.PowerShell.PSResourceGet and Pester

  - ${{ parameters.powershellExecutable }}: |
      $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
      $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
      Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
      Import-Module -Name (Join-Path -Path '${{ parameters.buildDirectory }}' -ChildPath 'buildtools.psd1') -Force
      #
      Install-ModulePackageForTest -PackagePath "$(System.ArtifactsDirectory)" -ErrorAction stop -Verbose
    displayName: Install module for test from downloaded artifact
    workingDirectory: ${{ parameters.buildDirectory }}

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: PSResourceGetACR
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      pwsh: true
      inline: |
        Write-Verbose -Verbose "Setting up secret for Azure Artifacts Credential Provider"
        $azt = Get-AzAccessToken

        $ADORepoName = "psrg-credprovidertest"
        $ADORepoUri = "https://pkgs.dev.azure.com/powershell-rel/PSResourceGet/_packaging/psrg-credprovidertest/nuget/v2"

        
        $VSS_NUGET_EXTERNAL_FEED_ENDPOINTS = "{'endpointCredentials': [{'endpoint':$($ADORepoUri), 'username': 'AzureDevOps', 'password':$($azt.Token)}]}"

        $vstsCommandString = "vso[task.setvariable variable=VSS_NUGET_EXTERNAL_FEED_ENDPOINTS]$VSS_NUGET_EXTERNAL_FEED_ENDPOINTS"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
        $plain = ConvertFrom-SecureString $($azt.Token) -AsPlainText
        write-host "plain: $plain"
    displayName: 'Setup Azure Artifacts Credential Provider secret'
    condition: eq(${{ parameters.useAzAuth }}, false)

  - pwsh: |
      Get-ChildItem -Path env: | Out-String -width 9999 -Stream | Write-Verbose -Verbose
    displayName: Capture environment 

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: PSResourceGetACR
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      pwsh: true
      inline: |
        Write-Verbose -Verbose "Getting Azure Container Registry"
        Get-AzContainerRegistry -ResourceGroupName 'PSResourceGet' -Name 'psresourcegettest' | Select-Object -Property *
        Write-Verbose -Verbose "Setting up secret for Azure Container Registry"
        $azt = Get-AzAccessToken
        $tenantId = $azt.TenantID
        Set-Secret -Name $tenantId -Secret $azt.Token -Verbose
        $vstsCommandString = "vso[task.setvariable variable=TenantId]$tenantId"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
    displayName: 'Setup Azure Container Registry secret'
    condition: eq(${{ parameters.useAzAuth }}, false)

  - powershell: |
      # Set environment variable to identify in tests that secret store should not be used.
        $vstsCommandString = "vso[task.setvariable variable=UsingAzAuth]true"
        Write-Host "sending " + $vstsCommandString
        Write-Host "##$vstsCommandString"
    displayName: 'Set UsingAzAuth environment variable'
    condition: eq(${{ parameters.useAzAuth }}, true)

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: PSResourceGetACR
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      inline: |
        $acrRepositoryNamesFolder = Join-Path -Path ([Environment]::GetFolderPath([System.Environment+SpecialFolder]::LocalApplicationData)) -ChildPath 'TempModules'
        Write-Verbose -Verbose "Creating new folder for acr repository names file to be placed with path: $acrRepositoryNamesFolder"
        $null = New-Item -Path $acrRepositoryNamesFolder -ItemType Directory
        $acrRepositoryNamesFilePath = Join-Path -Path $acrRepositoryNamesFolder -ChildPath 'ACRTestRepositoryNames.txt'
        New-Item -Path $acrRepositoryNamesFilePath
    displayName: 'Upload empty file for ACR functional tests to write test repository names to'

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: PSResourceGetACR
      azurePowerShellVersion: LatestVersion
      pwsh: true
      ScriptType: InlineScript
      inline: |
        $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
        $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath

        Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
        Import-Module -Name (Join-Path -Path '${{ parameters.buildDirectory }}' -ChildPath 'buildtools.psd1') -Force
        Invoke-ModuleTestsACR -Type Functional
    env:
      MAPPED_GITHUB_PAT: $(github_pat)
      MAPPED_ADO_PUBLIC_PAT: $(ado_public_pat)
      MAPPED_ADO_PRIVATE_PAT: $(ado_private_pat)
      MAPPED_ADO_PRIVATE_REPO_URL: $(ado_private_repo_url)
    displayName: 'Execute functional tests with AzAuth'
    condition: eq(${{ parameters.useAzAuth }}, true)

  - ${{ parameters.powershellExecutable }}: |
      $modulePath = Join-Path -Path $env:AGENT_TEMPDIRECTORY -ChildPath 'TempModules'
      $env:PSModulePath = $modulePath + [System.IO.Path]::PathSeparator + $env:PSModulePath
      Write-Verbose -Verbose "Importing build utilities (buildtools.psd1)"
      Import-Module -Name (Join-Path -Path '${{ parameters.buildDirectory }}' -ChildPath 'buildtools.psd1') -Force
      Invoke-ModuleTests -Type Functional
    env:
      MAPPED_GITHUB_PAT: $(github_pat)
      MAPPED_ADO_PUBLIC_PAT: $(ado_public_pat)
      MAPPED_ADO_PRIVATE_PAT: $(ado_private_pat)
      MAPPED_ADO_PRIVATE_REPO_URL: $(ado_private_repo_url)
    displayName: Execute functional tests
    workingDirectory: ${{ parameters.buildDirectory }}
    errorActionPreference: continue
    condition: eq(${{ parameters.useAzAuth }}, false)

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: PSResourceGetACR
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      inline: |
        $registryName = 'psresourcegettest'
        $acrRepositoryNamesFolder = Join-Path -Path ([Environment]::GetFolderPath([System.Environment+SpecialFolder]::LocalApplicationData)) -ChildPath 'TempModules'
        $acrRepositoryNamesFilePath = Join-Path -Path $acrRepositoryNamesFolder -ChildPath 'ACRTestRepositoryNames.txt'
        $repositoryNames = Get-Content -Path $acrRepositoryNamesFilePath
        foreach ($name in $repositoryNames)
        {
          # Delete images in the repository (including tags, unique layers, manifests) created for ACR tests
          Remove-AzContainerRegistryRepository -Name $name -RegistryName $registryName
        }
    displayName: 'Delete test repositories from ACR'
