blank_issues_enabled: false
contact_links:
  - name: Documentation Issue
    url: https://github.com/MicrosoftDocs/PowerShell-Docs
    about: Please open issues on documentation for PowerShellGet here.
