name: Release Checklist 🚀
description: Maintainers Only - Release Checklist
labels: Needs-Triage
body:
- type: markdown
  attributes:
    value: >
      This template is for maintainers to create an issues to track the release process.
      Please **only** use this template if you are a maintainer. 
- type: checkboxes
  attributes:
    label: Before Releasing
    options:
    - label: If necessary, update help docs using PlatyPS module (in a separate PR).
      required: true
    - label: Use release tool to update CHANGELOG.md and PSResourceGet.psd1.  
             Run 'Import-Module PSResourceGet\tool\releaseTools.psm1'.  
             Run 'Update-Changelog' and 'Update-PSDFile'.
      required: true
    - label: Manually update PSResourceGet version in the PSResourceGet.csproj.
      required: true
- type: checkboxes
  attributes:
    label: Kick off Test Release
    options:
    - label: Make sure the latest [AutoBuild pipeline](https://dev.azure.com/powershell-rel/PowerShellGetV3/_build) is green.
      required: true
    - label: Run [mirror pipeline](https://dev.azure.com/powershell-rel/PowerShellGetV3/_build?definitionId=30&_a=summary).
      required: true
    - label:  Kick off a test [release pipeline](https://dev.azure.com/powershell-rel/PowerShellGetV3/_build?definitionId=13) by clicking 'Run Pipeline' and ensuring that 'Publish' is set to 'False'.  
              Hit 'Run' to start the pipeline.  
              ⚠️ Note that this will NOT publish to the PowerShell Gallery, but will create a package in artifact drop that you can manually download and test before publishing to the PowerShell Gallery.
      required: true
    - label: Test module created through the release pipeline.
      required: true
- type: checkboxes
  attributes:
    label: Release
    options:
    - label: Kick off full release pipeline.
      required: true
    - label: Kick off a [release pipeline](https://dev.azure.com/powershell-rel/PowerShellGetV3/_build?definitionId=13) by clicking 'Run Pipeline' and ensuring that 'Publish' is set to 'True'.  
             Hit 'Run' to start the pipeline.  
             ⚠️ Note that this will publish to the PowerShell Gallery.
      required: true
    - label: After the release pipeline has completed test by installing from the PowerShell Gallery.
      required: true
