
[ClassVersion("1.0.0.0"),FriendlyName("PSModule")] 
class MSFT_PSModule : OMI_BaseResource
{
  [Key] String Name;
  [Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
  [Write] String Repository;
  [Write,ValueMap{"Trusted", "Untrusted"},Values{"Trusted", "Untrusted"}] String InstallationPolicy;
  [Write] Boolean Trusted;
  [Write] String Version;
  [Write] Boolean NoClobber;
  [Write] Boolean SkipPublisherCheck;
  [Read] string Description;
  [Read] String InstalledVersion;
  [Read] String Guid;
  [Read] String ModuleBase;
  [Read] String ModuleType;
  [Read] String Author;
};
