#################################################################################
#                               OneBranch Pipelines                             #
# Documentation:  https://aka.ms/onebranchrelease                               #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Support:        https://aka.ms/onebranchsupport                               #
#################################################################################
name: PSResourceGet-Release-Official-$(Build.BuildId)
trigger: none # https://aka.ms/obpipelines/triggers
pr:
  branches:
    include:
    - master
    - release*

parameters: # parameters are shown up in ADO UI in a build queue time
  - name: 'debug'
    displayName: 'Enable debug output'
    type: boolean
    default: false
  - name: 'rolloutType'
    displayName: 'SDP rollout type'
    type: string
    default: 'normal'
    values:
      - normal
      - emergency
      - globaloutage
  - name: 'overrideManagedValidationDuration'
    displayName: 'Override standard SDP duration?'
    type: boolean
    default: false
  - name: 'managedValidationDurationInHours'
    displayName: 'Override standard SDP duration (in hours)'
    type: number
    default: 0
  - name: 'icmIncidentId'
    displayName: 'IcM Incident Id'
    type: number
    default: 0

variables:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1
  - name: POWERSHELL_TELEMETRY_OPTOUT
    value: 1
  - name: ob_sdl_tsa_configFile
    value: $(Build.SourcesDirectory)\.config\tsaoptions.json
  - name: WindowsContainerImage
    value: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest # Docker image which is used to build the project https://aka.ms/obpipelines/containers
  - name: LinuxContainerImage
    value: mcr.microsoft.com/onebranch/azurelinux/build:3.0

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
      # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example#define-a-pipelines-resource

  pipelines:
  - pipeline: PSResourceGetBuild 
    source: PSResourceGet-Official

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates  # The Official template may only be used by Production-classified pipelines
  parameters:
    featureFlags:
      linuxEsrpSigning: true
    globalSdl:
      tsaOptionsFile: .config\tsaoptions.json
    ev2ManagedSdpRolloutConfig:
      rolloutType: ${{parameters.rolloutType}}
      overrideManagedValidationDuration: ${{parameters.overrideManagedValidationDuration}}
      managedValidationOverrideDurationInHours: ${{parameters.managedValidationDurationInHours}}
      icmIncidentId: ${{parameters.icmIncidentId}}

    stages:
      - template: /.pipelines/templates/release-publish-mar.yml@self

